// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { myPostsCreate, myPostsList, myPostsRemove, myPostsUpdate, type Options, publicPostsList, systemHealth, systemReady } from '../sdk.gen';
import type { MyPostsCreateData, MyPostsCreateError, MyPostsCreateResponse, MyPostsListData, MyPostsListError, MyPostsListResponse, MyPostsRemoveData, MyPostsRemoveError, MyPostsRemoveResponse, MyPostsUpdateData, MyPostsUpdateError, MyPostsUpdateResponse, PageCursor, PublicPostsListData, PublicPostsListError, PublicPostsListResponse, SystemHealthData, SystemHealthResponse, SystemReadyData, SystemReadyError, SystemReadyResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const systemHealthQueryKey = (options?: Options<SystemHealthData>) => createQueryKey('systemHealth', options);

export const systemHealthOptions = (options?: Options<SystemHealthData>) => queryOptions<SystemHealthResponse, DefaultError, SystemHealthResponse, ReturnType<typeof systemHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await systemHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: systemHealthQueryKey(options)
});

export const systemReadyQueryKey = (options?: Options<SystemReadyData>) => createQueryKey('systemReady', options);

export const systemReadyOptions = (options?: Options<SystemReadyData>) => queryOptions<SystemReadyResponse, SystemReadyError, SystemReadyResponse, ReturnType<typeof systemReadyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await systemReady({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: systemReadyQueryKey(options)
});

export const publicPostsListQueryKey = (options?: Options<PublicPostsListData>) => createQueryKey('publicPostsList', options);

export const publicPostsListOptions = (options?: Options<PublicPostsListData>) => queryOptions<PublicPostsListResponse, PublicPostsListError, PublicPostsListResponse, ReturnType<typeof publicPostsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await publicPostsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: publicPostsListQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const publicPostsListInfiniteQueryKey = (options?: Options<PublicPostsListData>): QueryKey<Options<PublicPostsListData>> => createQueryKey('publicPostsList', options, true);

export const publicPostsListInfiniteOptions = (options?: Options<PublicPostsListData>) => {
    const opts = infiniteQueryOptions<PublicPostsListResponse, PublicPostsListError, InfiniteData<PublicPostsListResponse>, QueryKey<Options<PublicPostsListData>>, PageCursor | Pick<QueryKey<Options<PublicPostsListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<PublicPostsListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    cursor: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await publicPostsList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: publicPostsListInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const myPostsListQueryKey = (options?: Options<MyPostsListData>) => createQueryKey('myPostsList', options);

export const myPostsListOptions = (options?: Options<MyPostsListData>) => queryOptions<MyPostsListResponse, MyPostsListError, MyPostsListResponse, ReturnType<typeof myPostsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await myPostsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: myPostsListQueryKey(options)
});

export const myPostsListInfiniteQueryKey = (options?: Options<MyPostsListData>): QueryKey<Options<MyPostsListData>> => createQueryKey('myPostsList', options, true);

export const myPostsListInfiniteOptions = (options?: Options<MyPostsListData>) => {
    const opts = infiniteQueryOptions<MyPostsListResponse, MyPostsListError, InfiniteData<MyPostsListResponse>, QueryKey<Options<MyPostsListData>>, PageCursor | Pick<QueryKey<Options<MyPostsListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<MyPostsListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    cursor: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await myPostsList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: myPostsListInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const myPostsCreateMutation = (options?: Partial<Options<MyPostsCreateData>>): UseMutationOptions<MyPostsCreateResponse, MyPostsCreateError, Options<MyPostsCreateData>> => {
    const mutationOptions: UseMutationOptions<MyPostsCreateResponse, MyPostsCreateError, Options<MyPostsCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await myPostsCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const myPostsRemoveMutation = (options?: Partial<Options<MyPostsRemoveData>>): UseMutationOptions<MyPostsRemoveResponse, MyPostsRemoveError, Options<MyPostsRemoveData>> => {
    const mutationOptions: UseMutationOptions<MyPostsRemoveResponse, MyPostsRemoveError, Options<MyPostsRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await myPostsRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const myPostsUpdateMutation = (options?: Partial<Options<MyPostsUpdateData>>): UseMutationOptions<MyPostsUpdateResponse, MyPostsUpdateError, Options<MyPostsUpdateData>> => {
    const mutationOptions: UseMutationOptions<MyPostsUpdateResponse, MyPostsUpdateError, Options<MyPostsUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await myPostsUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
