// This file is auto-generated by @hey-api/openapi-ts

import { http, type HttpHandler, HttpResponse, type HttpResponseResolver, type RequestHandlerOptions as RequestHandlerOptions2 } from 'msw';

import type { ClientOptions, MyPostsCreateData, MyPostsCreateResponses, MyPostsListResponses, MyPostsRemoveResponses, MyPostsUpdateData, MyPostsUpdateResponses, PublicPostsListResponses, SystemHealthResponses, SystemReadyResponses } from './types.gen';

export type RequestHandlerOptions = RequestHandlerOptions2 & {
  baseUrl?: ClientOptions['baseUrl'];
  responseFallback?: 'error' | 'passthrough';
};

export type HandleSystemHealthResponse = {
  body: SystemHealthResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/health` operation.
 */
export function handleSystemHealth(response?: HandleSystemHealthResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
  return http.get<never, never>(`${options?.baseUrl ?? '*'}/api/health`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 200 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type HandleSystemReadyResponse = {
  body: SystemReadyResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/ready` operation.
 */
export function handleSystemReady(response?: HandleSystemReadyResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
  return http.get<never, never>(`${options?.baseUrl ?? '*'}/api/ready`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 200 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type HandlePublicPostsListResponse = {
  body: PublicPostsListResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/posts` operation.
 */
export function handlePublicPostsList(response?: HandlePublicPostsListResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
  return http.get<never, never>(`${options?.baseUrl ?? '*'}/api/posts`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 200 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type HandleMyPostsListResponse = {
  body: MyPostsListResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /api/me/posts` operation.
 */
export function handleMyPostsList(response?: HandleMyPostsListResponse | HttpResponseResolver<never, never>, options?: RequestHandlerOptions): HttpHandler {
  return http.get<never, never>(`${options?.baseUrl ?? '*'}/api/me/posts`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 200 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type HandleMyPostsCreateResponse = {
  body: MyPostsCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /api/me/posts` operation.
 */
export function handleMyPostsCreate(response?: HandleMyPostsCreateResponse | HttpResponseResolver<never, MyPostsCreateData['body']>, options?: RequestHandlerOptions): HttpHandler {
  return http.post<never, MyPostsCreateData['body']>(`${options?.baseUrl ?? '*'}/api/me/posts`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 201 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type HandleMyPostsRemoveResponse = {
  body: MyPostsRemoveResponses[204];
  status?: 204;
};

/**
 * Handler for the `DELETE /api/me/posts/{id}` operation.
 */
export function handleMyPostsRemove(response?: HandleMyPostsRemoveResponse | HttpResponseResolver<{
  id: string;
}, never>, options?: RequestHandlerOptions): HttpHandler {
  return http.delete<{
    id: string;
  }, never>(`${options?.baseUrl ?? '*'}/api/me/posts/:id`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return new HttpResponse(body, { status: response?.status ?? 204 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type HandleMyPostsUpdateResponse = {
  body: MyPostsUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PATCH /api/me/posts/{id}` operation.
 */
export function handleMyPostsUpdate(response?: HandleMyPostsUpdateResponse | HttpResponseResolver<{
  id: string;
}, MyPostsUpdateData['body']>, options?: RequestHandlerOptions): HttpHandler {
  return http.patch<{
    id: string;
  }, MyPostsUpdateData['body']>(`${options?.baseUrl ?? '*'}/api/me/posts/:id`, info => {
    if (typeof response === 'function') {
      return response(info);
    }
    const body = response?.body;
    if (body !== undefined) {
      return HttpResponse.json(body, { status: response?.status ?? 200 });
    }
    if (options?.responseFallback === 'passthrough') {
      return;
    }
    return new Response('Not Implemented', {
      status: 501,
      statusText: 'Not Implemented'
    });
  }, options);
}

export type MswHandlerFactories = {
  /**
   * Handler for the `GET /api/health` operation.
   */
  systemHealth: typeof handleSystemHealth;
  /**
   * Handler for the `GET /api/ready` operation.
   */
  systemReady: typeof handleSystemReady;
  /**
   * Handler for the `GET /api/posts` operation.
   */
  publicPostsList: typeof handlePublicPostsList;
  /**
   * Handler for the `GET /api/me/posts` operation.
   */
  myPostsList: typeof handleMyPostsList;
  /**
   * Handler for the `POST /api/me/posts` operation.
   */
  myPostsCreate: typeof handleMyPostsCreate;
  /**
   * Handler for the `DELETE /api/me/posts/{id}` operation.
   */
  myPostsRemove: typeof handleMyPostsRemove;
  /**
   * Handler for the `PATCH /api/me/posts/{id}` operation.
   */
  myPostsUpdate: typeof handleMyPostsUpdate;
};

export type CreateMswHandlersResult = {
  all: (options?: {
    pick?: {
      [K in keyof MswHandlerFactories]?: Parameters<MswHandlerFactories[K]>[0] | Parameters<MswHandlerFactories[K]>;
    };
  }) => ReadonlyArray<HttpHandler>;
  pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
  type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
  function wrap<R>(handler: Handler<R>): Handler<R> {
    return (response, options) => handler(response, { ...config, ...options });
  }
  const pick: CreateMswHandlersResult['pick'] = {
    systemHealth: wrap(handleSystemHealth),
    systemReady: wrap(handleSystemReady),
    publicPostsList: wrap(handlePublicPostsList),
    myPostsList: wrap(handleMyPostsList),
    myPostsCreate: wrap(handleMyPostsCreate),
    myPostsRemove: wrap(handleMyPostsRemove),
    myPostsUpdate: wrap(handleMyPostsUpdate)
  };
  const all: CreateMswHandlersResult['all'] = (options = {}) => {
    type OverrideValue<R> = R | [
      response?: R,
      options?: RequestHandlerOptions
    ];
    function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
      return Array.isArray(override) ? fn(...override) : fn(override);
    }
    const overrides = options.pick ?? {};
    return [
      invoke(pick.myPostsRemove, overrides.myPostsRemove),
      invoke(pick.myPostsUpdate, overrides.myPostsUpdate),
      invoke(pick.myPostsList, overrides.myPostsList),
      invoke(pick.myPostsCreate, overrides.myPostsCreate),
      invoke(pick.systemHealth, overrides.systemHealth),
      invoke(pick.systemReady, overrides.systemReady),
      invoke(pick.publicPostsList, overrides.publicPostsList)
    ];
  };
  return { all, pick };
}
