// This file is auto-generated by @hey-api/openapi-ts
// fallow-ignore-file security-sink

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Health = {
  status: 'ok';
};

export type ServiceUnavailableEncoded = {
  _tag: 'ServiceUnavailable';
  message: string;
};

/**
 * The signed-in user, without credentials or session data.
 */
export type User = {
  id: string;
  name: string;
  email: string;
};

export type UnauthorizedEncoded = {
  _tag: 'Unauthorized';
  message: string;
};

/**
 * Opaque cursor from `nextCursor` of the previous page. Omit it for the first page.
 */
export type PageCursor = string;

export type Post = {
  id: string;
  body: string;
  authorName: string;
  createdAt: string;
  updatedAt: string;
};

/**
 * One page of posts, newest first. `nextCursor` is null on the last page.
 */
export type PostPage = {
  items: Array<Post>;
  nextCursor: PageCursor | null;
};

export type ValidationIssue = {
  path: Array<string>;
  message: string;
};

export type ValidationErrorEncoded = {
  _tag: 'ValidationError';
  message: string;
  issues: Array<ValidationIssue>;
};

export type PostInput = {
  body: unknown;
};

export type RateLimitedEncoded = {
  _tag: 'RateLimited';
  message: string;
  /**
   * Seconds until the next request can succeed.
   */
  retryAfter: number;
};

export type PostNotFoundEncoded = {
  _tag: 'PostNotFound';
  id: string;
};

export type SystemHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type SystemHealthResponses = {
  /**
   * Health
   */
  200: Health;
};

export type SystemHealthResponse = SystemHealthResponses[keyof SystemHealthResponses];

export type SystemReadyData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/ready';
};

export type SystemReadyErrors = {
  /**
   * ServiceUnavailable
   */
  503: ServiceUnavailableEncoded;
};

export type SystemReadyError = SystemReadyErrors[keyof SystemReadyErrors];

export type SystemReadyResponses = {
  /**
   * Health
   */
  200: Health;
};

export type SystemReadyResponse = SystemReadyResponses[keyof SystemReadyResponses];

export type MeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/me';
};

export type MeGetErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedEncoded;
};

export type MeGetError = MeGetErrors[keyof MeGetErrors];

export type MeGetResponses = {
  /**
   * The signed-in user, without credentials or session data.
   */
  200: User;
};

export type MeGetResponse = MeGetResponses[keyof MeGetResponses];

export type PublicPostsListData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: PageCursor;
    /**
     * Items per page, 1 to 50. Default 20.
     */
    limit?: string;
  };
  url: '/api/posts';
};

export type PublicPostsListErrors = {
  /**
   * ValidationError
   */
  400: ValidationErrorEncoded;
};

export type PublicPostsListError = PublicPostsListErrors[keyof PublicPostsListErrors];

export type PublicPostsListResponses = {
  /**
   * One page of posts, newest first. `nextCursor` is null on the last page.
   */
  200: PostPage;
};

export type PublicPostsListResponse = PublicPostsListResponses[keyof PublicPostsListResponses];

export type MyPostsListData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: PageCursor;
    /**
     * Items per page, 1 to 50. Default 20.
     */
    limit?: string;
  };
  url: '/api/me/posts';
};

export type MyPostsListErrors = {
  /**
   * ValidationError
   */
  400: ValidationErrorEncoded;
  /**
   * Unauthorized
   */
  401: UnauthorizedEncoded;
};

export type MyPostsListError = MyPostsListErrors[keyof MyPostsListErrors];

export type MyPostsListResponses = {
  /**
   * One page of posts, newest first. `nextCursor` is null on the last page.
   */
  200: PostPage;
};

export type MyPostsListResponse = MyPostsListResponses[keyof MyPostsListResponses];

export type MyPostsCreateData = {
  body: PostInput;
  path?: never;
  query?: never;
  url: '/api/me/posts';
};

export type MyPostsCreateErrors = {
  /**
   * ValidationError
   */
  400: ValidationErrorEncoded;
  /**
   * Unauthorized
   */
  401: UnauthorizedEncoded;
  /**
   * RateLimited
   */
  429: RateLimitedEncoded;
};

export type MyPostsCreateError = MyPostsCreateErrors[keyof MyPostsCreateErrors];

export type MyPostsCreateResponses = {
  /**
   * Success
   */
  201: Post;
};

export type MyPostsCreateResponse = MyPostsCreateResponses[keyof MyPostsCreateResponses];

export type MyPostsRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/me/posts/{id}';
};

export type MyPostsRemoveErrors = {
  /**
   * Unauthorized
   */
  401: UnauthorizedEncoded;
  /**
   * PostNotFound
   */
  404: PostNotFoundEncoded;
  /**
   * RateLimited
   */
  429: RateLimitedEncoded;
};

export type MyPostsRemoveError = MyPostsRemoveErrors[keyof MyPostsRemoveErrors];

export type MyPostsRemoveResponses = {
  /**
   * <No Content>
   */
  204: void;
};

export type MyPostsRemoveResponse = MyPostsRemoveResponses[keyof MyPostsRemoveResponses];

export type MyPostsUpdateData = {
  body: PostInput;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/me/posts/{id}';
};

export type MyPostsUpdateErrors = {
  /**
   * ValidationError
   */
  400: ValidationErrorEncoded;
  /**
   * Unauthorized
   */
  401: UnauthorizedEncoded;
  /**
   * PostNotFound
   */
  404: PostNotFoundEncoded;
  /**
   * RateLimited
   */
  429: RateLimitedEncoded;
};

export type MyPostsUpdateError = MyPostsUpdateErrors[keyof MyPostsUpdateErrors];

export type MyPostsUpdateResponses = {
  /**
   * Post
   */
  200: Post;
};

export type MyPostsUpdateResponse = MyPostsUpdateResponses[keyof MyPostsUpdateResponses];
