// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Health = {
    status: 'ok';
};

export type ServiceUnavailableEncoded = {
    _tag: 'ServiceUnavailable';
    message: string;
};

export type Post = {
    id: string;
    body: string;
    authorName: string;
    createdAt: string;
    updatedAt: string;
};

export type UnauthorizedEncoded = {
    _tag: 'Unauthorized';
    message: string;
};

export type PostInput = {
    body: string;
};

export type ValidationIssue = {
    path: Array<string>;
    message: string;
};

export type ValidationErrorEncoded = {
    _tag: 'ValidationError';
    message: string;
    issues: Array<ValidationIssue>;
};

export type PostNotFoundEncoded = {
    _tag: 'PostNotFound';
    id: string;
};

export type SystemHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type SystemHealthResponses = {
    /**
     * Health
     */
    200: Health;
};

export type SystemHealthResponse = SystemHealthResponses[keyof SystemHealthResponses];

export type SystemReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ready';
};

export type SystemReadyErrors = {
    /**
     * ServiceUnavailable
     */
    503: ServiceUnavailableEncoded;
};

export type SystemReadyError = SystemReadyErrors[keyof SystemReadyErrors];

export type SystemReadyResponses = {
    /**
     * Health
     */
    200: Health;
};

export type SystemReadyResponse = SystemReadyResponses[keyof SystemReadyResponses];

export type PublicPostsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/posts';
};

export type PublicPostsListResponses = {
    /**
     * Success
     */
    200: Array<Post>;
};

export type PublicPostsListResponse = PublicPostsListResponses[keyof PublicPostsListResponses];

export type MyPostsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/posts';
};

export type MyPostsListErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedEncoded;
};

export type MyPostsListError = MyPostsListErrors[keyof MyPostsListErrors];

export type MyPostsListResponses = {
    /**
     * Success
     */
    200: Array<Post>;
};

export type MyPostsListResponse = MyPostsListResponses[keyof MyPostsListResponses];

export type MyPostsCreateData = {
    body: PostInput;
    path?: never;
    query?: never;
    url: '/api/me/posts';
};

export type MyPostsCreateErrors = {
    /**
     * ValidationError
     */
    400: ValidationErrorEncoded;
    /**
     * Unauthorized
     */
    401: UnauthorizedEncoded;
};

export type MyPostsCreateError = MyPostsCreateErrors[keyof MyPostsCreateErrors];

export type MyPostsCreateResponses = {
    /**
     * Success
     */
    201: Post;
};

export type MyPostsCreateResponse = MyPostsCreateResponses[keyof MyPostsCreateResponses];

export type MyPostsRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/me/posts/{id}';
};

export type MyPostsRemoveErrors = {
    /**
     * ValidationError
     */
    400: ValidationErrorEncoded;
    /**
     * Unauthorized
     */
    401: UnauthorizedEncoded;
    /**
     * PostNotFound
     */
    404: PostNotFoundEncoded;
};

export type MyPostsRemoveError = MyPostsRemoveErrors[keyof MyPostsRemoveErrors];

export type MyPostsRemoveResponses = {
    /**
     * <No Content>
     */
    204: void;
};

export type MyPostsRemoveResponse = MyPostsRemoveResponses[keyof MyPostsRemoveResponses];

export type MyPostsUpdateData = {
    body: PostInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/me/posts/{id}';
};

export type MyPostsUpdateErrors = {
    /**
     * ValidationError
     */
    400: ValidationErrorEncoded;
    /**
     * Unauthorized
     */
    401: UnauthorizedEncoded;
    /**
     * PostNotFound
     */
    404: PostNotFoundEncoded;
};

export type MyPostsUpdateError = MyPostsUpdateErrors[keyof MyPostsUpdateErrors];

export type MyPostsUpdateResponses = {
    /**
     * Post
     */
    200: Post;
};

export type MyPostsUpdateResponse = MyPostsUpdateResponses[keyof MyPostsUpdateResponses];
